esp32-1.0.2/libraries/BluetoothSerial/README.md libraries/Communications/esp32/BluetoothSerial
esp32-1.0.2/libraries/BluetoothSerial/examples/ libraries/Communications/esp32/BluetoothSerial
esp32-1.0.2/libraries/BluetoothSerial/keywords.txt libraries/Communications/esp32/BluetoothSerial
esp32-1.0.2/libraries/BluetoothSerial/library.properties libraries/Communications/esp32/BluetoothSerial
esp32-1.0.2/libraries/BluetoothSerial/src/ libraries/Communications/esp32/BluetoothSerial
